settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: golog
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
- name: pack
  path: .
  watcher:
    paths:
      - public/js/
    extensions:
      - js
      - vue
    scripts:
      - type: after
        command: node node_modules/browserify/bin/cmd.js public/js/panel.js -o public/dist/panel.js -d --fast